### ISSUE TITLE
Sliders getting stuck after first input?

### ISSUE THREAD

**Issue by Th3Shr00m** [lyuma/Av3Emulator#18] opened 2021-10-11 07:22 UTC
Hey Lyuma, I have a problem that nobody else seems to get. Whenever I try to move one of the sliders (for instance GestureRight), it will not move from the first given input unless I exit and re-enter play mode. I've tried resetting the avatar, inputting values manually, and reinstalling the entire emulator with no luck. Not quite sure what to do. Some of them work, but others don't and I'm just at a loss. I've attached a Gyazo link for clarity. Currently using Unity version 2019.4.31f1 and SDK version 2021.03.22.18.27. Thanks!

https://gyazo.com/4babfc03001d1f26f272b215c3d256bc

**Comment by jellejurre** [comment] 2023-03-22 18:49
Closed as I'm unable to reproduce

sounds like untiy being unity

**Closed by jellejurre** 2023-03-22 18:49 UTC
