### ISSUE TITLE
Emulator Defaults to Bicycle pose when using the Default Gesture Layer

### ISSUE THREAD

**Issue by Smash-ter** [lyuma/Av3Emulator#99] opened 2023-04-09 22:02 UTC
In testing with the newer version of the Av3Emulator (v3.1.0) there seems to be an issue when previewing the models that they default to the bicycle humanoid reference. This is likely happening because the emulator may be failing to recognize the default gesture layer properly. When using a custom gesture layer this problem is nonexistent.

https://user-images.githubusercontent.com/129467555/230798523-6ac29e9d-d83b-4ad6-bcaa-1f41f7922b1d.mp4

**Comment by lyuma** [comment] 2023-04-10 09:20
Smash-ter told me they use experimental enter play mode settings with Reload Domain off.
Duplicate of #92

**Closed by lyuma** 2023-04-10 09:20 UTC
